swagger: '2.0'
info:
  title: Boilerplate Service
  version: "1.0.0"
host: service.boilerplate
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:

definitions:
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
    required: ["code"]
